# Generated by Django 3.2.3 on 2021-07-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='trail_length',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
