# Generated by Django 3.2.5 on 2021-07-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210712_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RST', 'Restroom'), ('BEN', 'Benches'), ('PIC', 'Picnic Tables'), ('VIS', 'Visitor Center'), ('DOG', 'Dog Friendly'), ('PLY', 'Playground'), ('WTR', 'Water Fountains'), ('BBQ', 'Barbeque Pit'), ('MTN', 'Mountain Biking'), ('RNG', 'Running'), ('HIK', 'Hiking'), ('SWM', 'Swimming'), ('PTH', 'Nature Path'), ('CMP', 'Camping'), ('BRD', 'Bird Watching'), ('BGN', 'Begginer'), ('INT', 'Intermediate'), ('ADV', 'Advanced')], default='RST', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='trail',
            name='ammenities',
            field=models.ManyToManyField(to='main_app.Amenity'),
        ),
    ]
