# Generated by Django 3.2.5 on 2021-07-13 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210713_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='ammenities',
            new_name='amenities',
        ),
    ]
