# Generated by Django 3.2.3 on 2021-07-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20210714_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trail',
            options={'ordering': ['name']},
        ),
    ]
