# Generated by Django 3.2.5 on 2021-07-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_trail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Comment'),
        ),
    ]
